data:
  train_csv: data/train.csv
  target: label
  categorical: []

model:
  loss_function: Logloss
  iterations: 200
  learning_rate: 0.1
  depth: 6
  random_seed: 42
  verbose: false

fit:
  verbose: false


