data:
  train_json: testdata/instrument.json   # 也可用你自己的大文件
  target: label                          # 你的目标字段，需写入“不锈钢压力表”等真实类型
  # 建议显式列出特征，避免泄漏特征（id、时间戳、tag等）
  features:
    - function
    - instrument_type
    - instrument_name
    - location
    - assembly_material
    - assembly_installsize
    - assembly_substance
    - assembly_phase
    - assembly_density
    - process
    - direction
    - material
    - status
  categorical: auto                      # 自动将 object 列当作类别特征
model:
  loss_function: MultiClass
  iterations: 800
  learning_rate: 0.06
  depth: 8
  random_seed: 42
  verbose: false
fit:
  verbose: false